apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: caduunisal/meusite-contact:latest
        ports:
        - containerPort: 80

