apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: caduunisal/meusite-home:latest
        ports:
        - containerPort: 80

